name: main
on:
 push:
   branches:
     - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y ovmf qemu-system-arm qemu-efi-aarch64 qemu-system qemu-efi
        ls -ltra /usr/share/qemu/firmware/
